import { ReactNode } from 'react'
import './globals.css'
import { Poppins, Montserrat } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-poppins',
})
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Paquetá calçados',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable} ${montserrat.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
